  sleep: {
    screenTitle: 'Сон',
    sectionTitle: 'Качество среды за неделю',
    legendGood: 'Всё в норме',
    legendFair: 'Были отклонения',
    legendPoor: 'Заметные отклонения',
    legendNoData: 'Нет данных',
    weekNavOlderA11y: 'Предыдущая неделя',
    weekNavNewerA11y: 'Следующая неделя',
    nightCellA11y: '{weekday}, ночь',
    nightDetailTitle: 'Ночь',
    nightDetailEmpty: 'Недостаточно данных за эту ночь',
    metricTabs: {
      co2: 'CO₂',
      temperature: 'Температура',
      humidity: 'Влажность',
    },
    metricInsights: {
      co2: 'CO₂ был в норме {percent}% ночи',
      temperature: 'Температура была комфортной {percent}% ночи',
      humidity: 'Влажность была в норме {percent}% ночи',
    },
    noDataCell: '—',
    monthsShort: ['янв', 'фев', 'мар', 'апр', 'мая', 'июн', 'июл', 'авг', 'сен', 'окт', 'ноя', 'дек'],
    emptyWeek: 'Пока нет данных за эту неделю',
    loadError: 'Не получилось загрузить эту неделю',
    noSensorsHint: 'Настрой датчики в спальне — тогда появится история среды',
    metrics: {
      co2Range: 'CO₂ за ночь',
      tempAvg: 'Средняя температура',
      humidityAvg: 'Средняя влажность',
      ppmUnit: 'ppm',
    },
    scoreGood: 'Среда была комфортной',
    scoreFair: 'Были небольшие отклонения',
    scorePoor: 'Среда мешала отдыху',
    scoreNoData: 'Данных за эту ночь нет',
    nightSummaryOpenLabel: 'Подробнее',
    nightSummaryOpenA11y: 'Подробнее о ночи',
    nightSummarySheetEmpty: 'Дополнительных данных за эту ночь нет',
    issues: {
      co2High: 'Воздух был душным — CO₂ поднимался выше нормы',
      tempHigh: 'В спальне было жарковато',
      tempLow: 'В спальне было прохладно',
      humidityLow: 'Воздух был слишком сухим',
    },
    wearableUnavailable: 'Данные о сне с телефона доступны только на iPhone',
    wearableDenied: 'Нет доступа к данным о сне — разреши в настройках Здоровья',
    wearableNoData:
      'В Здоровье нет сна за эту ночь — проверь, что часы синхронизировались',
    wearableLoadError: 'Не удалось загрузить сон с часов — попробуй ещё раз',
    wearableLoading: 'Загружаем сон с часов…',
    wearableSectionTitle: 'Трекер',
    wearableOpenSettings: 'Открыть настройки',
    wearableOpenHealth: 'Открыть Здоровье',
    wearableBedtimeLabel: 'Засыпание — подъём',
    wearableTotalSleepLabel: 'Всего сна',
    wearableQualityLabel: 'Качество сна',
    wearableQualityExcellent: 'Отлично',
    wearableQualityGood: 'Хорошо',
    wearableQualityFair: 'Нормально',
    wearableQualityPoor: 'Прерывисто',
    wearableQualityValue: '{score} · {label}',
    wearableSleepNorm: 'Норма 7–9 ч',
    wearableBedtimeSeparator: ' – ',
    wearableScoreNightLabel: 'Оценка этой ночи',
    wearableScoreTrendLabel: 'Среднее за период',
    wearableScoreMethodology: 'Оценка приложения, не из Здоровья',
    wearableScoreTrend7: '7 дней',
    wearableScoreTrend30: '30 дней',
    wearableScoreCollecting: 'Собираем данные',
    wearableScoreBelowNorm: 'Сон короче рекомендованной нормы',
    wearableScoreDuration: 'Длительность',
    wearableScoreEfficiency: 'Эффективность',
    wearableScoreContinuity: 'Непрерывность',
    wearableScoreConsistency: 'Стабильность',
    wearableScoreComponentValue: '{score}',
    wearableScoreExplainA11y: 'Как считается {label}',
    wearableScoreDurationSheetTitle: 'Длительность',
    wearableScoreDurationTonight: 'Сон этой ночи',
    wearableScoreDurationUsual: 'Обычно за неделю',
    wearableScoreDurationNorm: 'Норма 7–9 ч',
    wearableScoreDurationAxis4: '4 ч',
    wearableScoreDurationAxis7: '7 ч',
    wearableScoreDurationAxis9: '9 ч',
    wearableScoreDurationAxis12: '12 ч',
    wearableScoreDurationBonus: 'Близко к обычному режиму — бонус +{bonus}',
    wearableScoreDurationBonusExact: 'Как обычно — бонус +{bonus}',
    wearableScoreDurationNoBaseline:
      'Персональный бонус появится, когда накопим неделю данных',
    wearableScoreDurationMissing: '—',
    wearableScoreConsistencySheetTitle: 'Стабильность',
    wearableScoreConsistencyBedtime: 'Отбой',
    wearableScoreConsistencyWake: 'Подъём',
    wearableScoreConsistencyStd: '± {minutes} мин',
    wearableScoreConsistencySpread: 'Средний разброс: {minutes} мин',
    wearableScoreConsistencyAxis0: '0 мин',
    wearableScoreConsistencyAxis15: '15 мин',
    wearableScoreConsistencyAxis90: '90 мин',
    wearableScoreConsistencyCollecting:
      'Нужно хотя бы 7 ночей с данными часов. Пока собираем — этот пункт не входит в оценку.',
    wearableScoreConsistencyNightsTitle: 'Отбой и подъём',
    wearableScoreConsistencyAxisTime: '{time}',
    roomConditionsTitle: 'Условия в комнате',
    wearableDurationHoursMinutes: '{hours} ч {minutes} мин',
    wearableDurationHoursOnly: '{hours} ч',
    wearableDurationMinutesOnly: '{minutes} мин',
  },