import {
  SKELETON_PULSE_OPACITY_MIN,
  SLEEP_NIGHT_DETAIL_SKELETON_PULSE,
} from '@/ui/skeletonPulse.const';

export const SLEEP_NIGHT_DETAIL_SKELETON = 'SleepNightDetailSkeleton' as const;

export const SLEEP_NIGHT_DETAIL_SKELETON_PULSE_MIN = SKELETON_PULSE_OPACITY_MIN;

export const SLEEP_NIGHT_DETAIL_SKELETON_PULSE_MAX = SLEEP_NIGHT_DETAIL_SKELETON_PULSE.max;

export const SLEEP_NIGHT_DETAIL_SKELETON_PULSE_MS = SLEEP_NIGHT_DETAIL_SKELETON_PULSE.durationMs;

export const SLEEP_NIGHT_DETAIL_CHART_HEIGHT = 200;
