import {
  SKELETON_PULSE_OPACITY_MIN,
  SLEEP_NIGHT_DETAIL_SKELETON_PULSE,
} from '@/ui/skeletonPulse.const';

export const ROOM_CONDITIONS_CHART_SKELETON = 'RoomConditionsChartSkeleton' as const;

export const ROOM_CONDITIONS_CHART_SKELETON_PULSE_MIN = SKELETON_PULSE_OPACITY_MIN;

export const ROOM_CONDITIONS_CHART_SKELETON_PULSE_MAX = SLEEP_NIGHT_DETAIL_SKELETON_PULSE.max;

export const ROOM_CONDITIONS_CHART_SKELETON_PULSE_MS = SLEEP_NIGHT_DETAIL_SKELETON_PULSE.durationMs;

/** Высота плейсхолдера графика, px */
export const ROOM_CONDITIONS_CHART_SKELETON_CHART_HEIGHT = 200;
