// eslint-disable-next-line @typescript-eslint/no-require-imports
const healthPermissions = require('./healthPermissions.js') as {
  shareUsageDescription: string;
};

export const copy = {
  common: {
    done: 'Готово',
    loadingA11y: 'Загрузка…',
  },
  units: {
    minutesShort: 'мин',
  },
  now: {
    screenTitle: 'Сейчас',
    setupSensorsHint: 'Настрой датчики в спальне — тогда увидишь температуру, влажность и CO₂.',
    setupSensorsButton: 'Открыть спальню',
    deviceActionFailed: 'Не получилось выполнить действие',
    scenarioUnavailable: 'Сценарий сейчас недоступен',
    activeScenarioExitA11y: 'Выключить режим «{label}»',
    preparedScenarioA11y: 'Дом готов. Повторить «{label}»',
    phrases: {
      stuffyVentilate: 'Душно — стоит проветрить',
      slightlyStuffy: 'Немного душновато',
      warmForSleep: 'Жарковато для сна',
      warmBedroom: 'Жарковато в спальне',
      coolBedroom: 'Прохладно в спальне',
      dryHumidifier: 'Суховато — увлажнитель поможет',
      comfortable: 'В спальне комфортно',
      noData: 'Данных пока нет',
      stuffyForSleep: 'Душно для сна — стоит проветрить',
      slightlyStuffyForSleep: 'Немного душновато для сна',
      coolForSleep: 'Прохладно для сна',
      dryForSleep: 'Суховато для сна — увлажнитель поможет',
      comfortableForSleep: 'Для сна сейчас комфортно',
    },
    metricsUnavailable: '—',
    metrics: {
      temperature: 'Температура',
      humidity: 'Влажность',
      co2: 'CO₂',
      pressure: 'Давление',
      ppmUnit: 'ppm',
      mmhgUnit: 'mmHg',
    },
    outdoorSectionTitle: 'Снаружи',
    outdoorMetrics: {
      temperature: 'Температура',
      sunset: 'Закат',
      sunrise: 'Восход',
    },
    suggestions: {
      stuffyForSleepVentilate: 'Душно для сна — проветрим?',
      slightlyStuffyVentilate: 'Душновато — проветрим?',
      openWindow: 'Открыть окно',
      dryHumidifierOn: 'Суховато — включить увлажнитель?',
      turnOnHumidifier: 'Включить увлажнитель',
      turnOnLight: 'Включить свет',
    },
  },
  quickActions: {
    manualControl: 'Ручное управление',
    manualControlRoom: 'Спальня',
    manualControlFailed: 'Не получилось изменить',
  },
  home: {
    screenTitle: 'Дом',
    lifeStateTitles: {
      morning: 'Доброе утро',
      evening: 'Спокойный вечер',
      sleep: 'Время отдыха',
      work: 'Рабочий ритм',
      rest: 'Дом в порядке',
      guests: 'Гости у нас',
      away: 'Дом ждёт тебя',
    },
  },
  connection: {
    noNetwork: 'Нет интернета — дом подождёт, пока связь вернётся',
    haUnavailable: 'Дом сейчас не отвечает',
    tokenExpired: 'Подключение устарело — обнови его в настройках',
    genericError: 'Не получилось связаться с домом',
    checking: 'Связываемся с домом…',
    retryAction: 'Проверить снова',
    reconnectAction: 'Обновить подключение',
    needUrl: 'Укажи адрес дома — локальный или удалённый',
  },
  scenarios: {
    sectionTitle: 'Сценарии',
    names: {
      evening: 'Вечер',
      sleep: 'Сон',
      morning: 'Утро',
      away: 'Уехали',
      coming_home: 'Еду домой',
      cozy: 'Уют',
      focus: 'Фокус',
    },
    scheduleToday: 'Сегодня в {time}',
    scheduleTomorrow: 'Завтра в {time}',
    scheduleWeekday: '{weekday} в {time}',
    weekdays: {
      mon: 'Пн',
      tue: 'Вт',
      wed: 'Ср',
      thu: 'Чт',
      fri: 'Пт',
      sat: 'Сб',
      sun: 'Вс',
    },
    runFailed: 'Не получилось запустить сценарий',
    writeFailed: 'Не получилось сохранить настройку',
    running: 'Запускаем…',
    preparing: 'Готовим дом…',
    activeNow: 'Сейчас активен',
    prepared: 'Дом готов к тебе',
    settingsA11y: 'Настроить сценарий',
    settingsPlaceholder: 'Настройки появятся в следующем обновлении',
    notFound: 'Сценарий не найден',
    runNow: 'Запустить сейчас',
    paramsSectionTitle: 'Параметры',
    scheduleSectionTitle: 'Расписание',
    missingHelper: 'Часть настроек пока недоступна',
    missingHelperHint: 'Установи пакет сценариев в доме — тогда здесь появятся все параметры.',
    descriptions: {
      evening: 'Приглушённый свет, комфортная температура и уют к вечеру.',
      sleep: 'Прохладно, тихо и свежий воздух для сна.',
      morning: 'Мягкий свет и тепло к пробуждению.',
      away: 'Дом в режиме ожидания, пока тебя нет.',
      coming_home: 'Подготовим дом к твоему приезду.',
      cozy: 'Тёплый свет и комфортная атмосфера.',
      focus: 'Яркий свет и прохладнее — для концентрации.',
    },
    settingsFields: {
      brightness: 'Яркость',
      temperature: 'Температура',
      nightTemperature: 'Ночная температура',
      curtains: 'Закрывать шторы',
      humidifier: 'Включать увлажнитель',
      window: 'Открывать окно',
      nightlight: 'Ночник',
      nightlightBrightness: 'Яркость ночника',
      nightlightColor: 'Цвет ночника',
      warmupMinutes: 'Плавное пробуждение',
      awayTemperature: 'Температура ожидания',
      minutes: 'За сколько минут',
      scheduleEnabled: 'По расписанию',
      scheduleTime: 'Время',
    },
  },
  notifications: {
    dismissLater: 'Не сейчас',
  },
  rooms: {
    sectionTitle: 'Комнаты',
    openRoomA11y: 'Открыть',
  },
  presence: {
    sectionTitle: 'Кто дома',
    empty: 'Никого дома',
  },
  timeline: {
    sectionTitle: 'День дома',
    empty: 'Пока тихо — событий нет',
  },
  sleep: {
    screenTitle: 'Сон',
    sectionTitle: 'Качество среды за неделю',
    legendGood: 'Всё в норме',
    legendFair: 'Были отклонения',
    legendPoor: 'Заметные отклонения',
    legendNoData: 'Нет данных',
    weekNavOlderA11y: 'Предыдущая неделя',
    weekNavNewerA11y: 'Следующая неделя',
    nightCellA11y: '{weekday}, ночь',
    nightDetailTitle: 'Ночь',
    nightDetailEmpty: 'Недостаточно данных за эту ночь',
    metricTabs: {
      co2: 'CO₂',
      temperature: 'Температура',
      humidity: 'Влажность',
    },
    metricInsights: {
      co2: 'CO₂ был в норме {percent}% ночи',
      temperature: 'Температура была комфортной {percent}% ночи',
      humidity: 'Влажность была в норме {percent}% ночи',
    },
    noDataCell: '—',
    monthsShort: ['янв', 'фев', 'мар', 'апр', 'мая', 'июн', 'июл', 'авг', 'сен', 'окт', 'ноя', 'дек'],
    emptyWeek: 'Пока нет данных за эту неделю',
    loadError: 'Не получилось загрузить эту неделю',
    noSensorsHint: 'Настрой датчики в спальне — тогда появится история среды',
    metrics: {
      co2Range: 'CO₂ за ночь',
      tempAvg: 'Средняя температура',
      humidityAvg: 'Средняя влажность',
      ppmUnit: 'ppm',
    },
    scoreGood: 'Среда была комфортной',
    scoreFair: 'Были небольшие отклонения',
    scorePoor: 'Среда мешала отдыху',
    scoreNoData: 'Данных за эту ночь нет',
    nightSummaryOpenLabel: 'Подробнее',
    nightSummaryOpenA11y: 'Подробнее о ночи',
    nightSummarySheetEmpty: 'Дополнительных данных за эту ночь нет',
    issues: {
      co2High: 'Воздух был душным — CO₂ поднимался выше нормы',
      tempHigh: 'В спальне было жарковато',
      tempLow: 'В спальне было прохладно',
      humidityLow: 'Воздух был слишком сухим',
    },
    wearableUnavailable: 'Данные о сне с телефона доступны только на iPhone',
    wearableDenied: 'Нет доступа к данным о сне — разреши в настройках Здоровья',
    wearableNoData:
      'В Здоровье нет сна за эту ночь — проверь, что часы синхронизировались',
    wearableLoadError: 'Не удалось загрузить сон с часов — попробуй ещё раз',
    wearableLoading: 'Загружаем сон с часов…',
    wearableSectionTitle: 'Трекер',
    wearableOpenSettings: 'Открыть настройки',
    wearableOpenHealth: 'Открыть Здоровье',
    wearableBedtimeLabel: 'Засыпание — подъём',
    wearableTotalSleepLabel: 'Всего сна',
    wearableQualityLabel: 'Качество сна',
    wearableQualityExcellent: 'Отличный',
    wearableQualityGood: 'Хороший',
    wearableQualityFair: 'Нормальный',
    wearableQualityPoor: 'Прерывистый',
    wearableQualityValue: '{score} · {label}',
    wearableSleepNorm: 'Норма 7–9 ч',
    wearableBedtimeSeparator: ' – ',
    roomConditionsTitle: 'Условия в комнате',
    wearableDurationHoursMinutes: '{hours} ч {minutes} мин',
    wearableDurationHoursOnly: '{hours} ч',
    wearableDurationMinutesOnly: '{minutes} мин',
  },
  health: {
    shareUsageDescription: healthPermissions.shareUsageDescription,
  },
  settings: {
    screenTitle: 'Настройки',
    syncTitle: 'Проверка данных',
    syncRefresh: 'Обновить данные',
    syncRefreshing: 'Загружаем…',
    haDevicesList: 'Список устройств',
    reconnect: 'Изменить подключение к дому',
    nightSchedule: {
      title: 'Границы ночи',
      hint: 'Используем для экрана «Сейчас», истории сна и графиков.',
      bedtimeLabel: 'Обычно ложусь',
      wakeTimeLabel: 'Обычно просыпаюсь',
    },
    bedroomDevices: {
      screenTitle: 'Устройства в спальне',
      hint: 'Выбери, что показывать на экране спальни. Привязку к дому настраивай шестерёнкой на карточке.',
      showInListA11y: 'Показывать в списке',
    },
  },
  sensorPicker: {
    screenTitle: 'Выбор датчика',
    searchPlaceholder: 'Поиск по названию…',
    loading: 'Загрузка…',
    emptySearch: 'Ничего не найдено',
    emptyList: 'Нет датчиков',
    shownCount: 'Показано: {shown}',
    recommended: 'Подходят',
    other: 'Остальные',
    nonNumericHint: 'Похоже, это не датчик с цифрами',
  },
  devicePicker: {
    screenTitle: 'Выбор устройства',
    searchPlaceholder: 'Поиск по названию…',
    loading: 'Загрузка…',
    emptySearch: 'Ничего не найдено',
    emptyList: 'Нет устройств',
    shownCount: 'Показано: {shown}',
    recommended: 'Подходят',
    other: 'Остальные',
    statePreview: {
      on: 'Вкл',
      off: 'Выкл',
      open: 'Открыто',
      closed: 'Закрыто',
    },
  },
  bedroom: {
    screenTitle: 'Спальня',
    unavailable: 'Сейчас недоступен',
    setupDevicesButton: 'Состав устройств',
    configureDeviceA11y: 'Настроить устройство',
    colorPresetA11y: 'Цвет {index}',
    emptyDevicesHint: 'Включи устройства в составе — тогда ими можно управлять здесь.',
    tabs: {
      devices: 'Устройства',
      sensors: 'Датчики',
    },
    sensors: {
      configureA11y: 'Настроить датчик',
      notConfigured: 'Не выбрано',
      notUsed: 'Не используется',
    },
  },
  onboarding: {
    title: 'Подключи дом',
    subtitle: 'Home Assistant остаётся за кадром — ты видишь только уют.',
    remoteOnlyHint:
      'Только удалённый URL? Оставь локальный пустым — подключимся сразу к Nabu Casa.',
    name: 'Название',
    localUrl: 'Локальный URL (LAN)',
    remoteUrl: 'Удалённый URL (опционально)',
    token: 'Токен доступа',
    localUrlPlaceholder: 'http://192.168.x.x:8123 (опционально)',
    remoteUrlPlaceholder: 'https://….ui.nabu.casa',
    save: 'Сохранить',
  },
  notFound: {
    screenTitle: 'Страница не найдена',
    title: 'Такой страницы нет',
    link: 'На главную',
  },
  haEntities: {
    screenTitle: 'Список устройств',
    hint: 'Скопируй идентификатор устройства в config — ищи свет, датчики, людей',
    searchPlaceholder: 'Поиск: свет, датчик, кухня…',
    loading: 'Загрузка…',
    shownCount: 'Показано: {shown} из {total}',
    emptySearch: 'Ничего не найдено',
    emptyList: 'Список пуст',
  },
} as const;
