export const copy = {
  now: {
    screenTitle: 'Сейчас',
    setupSensorsHint: 'Настрой датчики в спальне — тогда увидишь температуру, влажность и CO₂.',
    setupSensorsButton: 'Открыть спальню',
    phrases: {
      stuffyVentilate: 'Душно — стоит проветрить',
      slightlyStuffy: 'Немного душновато',
      warmForSleep: 'Жарковато для сна',
      coolBedroom: 'Прохладно в спальне',
      dryHumidifier: 'Суховато — увлажнитель поможет',
      comfortable: 'В спальне комфортно',
      noData: 'Данных пока нет',
    },
    metricsUnavailable: '—',
    metrics: {
      temperature: 'Температура',
      humidity: 'Влажность',
      co2: 'CO₂',
    },
  },
  home: {
    screenTitle: 'Дом',
    defaultTitle: 'Дом в порядке',
    awayTitle: 'Дом ждёт тебя',
    guestsTitle: 'Гости у нас',
  },
  connection: {
    offline: 'Дом сейчас недоступен. Проверь сеть или URL.',
    checking: 'Связываемся с домом…',
    needUrl: 'Укажи хотя бы локальный или удалённый URL Home Assistant.',
  },
  rituals: {
    sectionTitle: 'Ритуалы',
    running: 'Запускаем…',
  },
  notifications: {
    dismissLater: 'Не сейчас',
  },
  rooms: {
    sectionTitle: 'Комнаты',
    openRoomA11y: 'Открыть',
  },
  presence: {
    sectionTitle: 'Кто дома',
    empty: 'Никого дома',
  },
  timeline: {
    sectionTitle: 'День дома',
    empty: 'Пока тихо — событий нет',
  },
  settings: {
    screenTitle: 'Настройки',
    syncTitle: 'Проверка данных',
    syncRefresh: 'Обновить данные',
    syncRefreshing: 'Загружаем…',
    haDevicesList: 'Список устройств',
    reconnect: 'Изменить подключение к дому',
    bedroomDevices: {
      screenTitle: 'Устройства в спальне',
      hint: 'Выбери, что показывать на экране спальни. Привязку к дому настраивай шестерёнкой на карточке.',
      showInListA11y: 'Показывать в списке',
    },
  },
  sensorPicker: {
    screenTitle: 'Выбор датчика',
    searchPlaceholder: 'Поиск по названию…',
    loading: 'Загрузка…',
    emptySearch: 'Ничего не найдено',
    emptyList: 'Нет датчиков',
    shownCount: 'Показано: {shown}',
    recommended: 'Подходят',
    other: 'Остальные',
    nonNumericHint: 'Похоже, это не датчик с цифрами',
  },
  devicePicker: {
    screenTitle: 'Выбор устройства',
    searchPlaceholder: 'Поиск по названию…',
    loading: 'Загрузка…',
    emptySearch: 'Ничего не найдено',
    emptyList: 'Нет устройств',
    shownCount: 'Показано: {shown}',
    recommended: 'Подходят',
    other: 'Остальные',
  },
  bedroom: {
    screenTitle: 'Спальня',
    unavailable: 'Сейчас недоступен',
    setupDevicesButton: 'Состав устройств',
    configureDeviceA11y: 'Настроить устройство',
    emptyDevicesHint: 'Включи устройства в составе — тогда ими можно управлять здесь.',
    tabs: {
      devices: 'Устройства',
      sensors: 'Датчики',
    },
    sensors: {
      configureA11y: 'Настроить датчик',
      notConfigured: 'Не выбрано',
      notUsed: 'Не используется',
    },
  },
  onboarding: {
    title: 'Подключи дом',
    subtitle: 'Home Assistant остаётся за кадром — ты видишь только уют.',
    remoteOnlyHint:
      'Только удалённый URL? Оставь локальный пустым — подключимся сразу к Nabu Casa.',
    name: 'Название',
    localUrl: 'Локальный URL (LAN)',
    remoteUrl: 'Удалённый URL (опционально)',
    token: 'Токен доступа',
    localUrlPlaceholder: 'http://192.168.x.x:8123 (опционально)',
    remoteUrlPlaceholder: 'https://….ui.nabu.casa',
    save: 'Сохранить',
  },
  notFound: {
    screenTitle: 'Страница не найдена',
    title: 'Такой страницы нет',
    link: 'На главную',
  },
  haEntities: {
    screenTitle: 'Список устройств',
    hint: 'Скопируй идентификатор устройства в config — ищи свет, датчики, людей',
    searchPlaceholder: 'Поиск: свет, датчик, кухня…',
    loading: 'Загрузка…',
    shownCount: 'Показано: {shown} из {total}',
    emptySearch: 'Ничего не найдено',
    emptyList: 'Список пуст',
  },
} as const;
