export const copy = {
  now: {
    screenTitle: 'Сейчас',
    setupSensorsHint: 'Подключи датчики спальни — тогда увидишь температуру, влажность и CO₂.',
    setupSensorsButton: 'Настроить датчики',
    phrases: {
      stuffyVentilate: 'Душно — стоит проветрить',
      slightlyStuffy: 'Немного душновато',
      warmForSleep: 'Жарковато для сна',
      coolBedroom: 'Прохладно в спальне',
      dryHumidifier: 'Суховато — увлажнитель поможет',
      comfortable: 'В спальне комфортно',
      noData: 'Данных пока нет',
    },
    metricsUnavailable: '—',
    metrics: {
      temperature: 'Температура',
      humidity: 'Влажность',
      co2: 'CO₂',
    },
  },
  home: {
    screenTitle: 'Дом',
    defaultTitle: 'Дом в порядке',
    awayTitle: 'Дом ждёт тебя',
    guestsTitle: 'Гости у нас',
  },
  connection: {
    offline: 'Дом сейчас недоступен. Проверь сеть или URL.',
    checking: 'Связываемся с домом…',
    needUrl: 'Укажи хотя бы локальный или удалённый URL Home Assistant.',
  },
  rituals: {
    sectionTitle: 'Ритуалы',
    running: 'Запускаем…',
  },
  notifications: {
    dismissLater: 'Не сейчас',
  },
  rooms: {
    sectionTitle: 'Комнаты',
    lightOn: 'Свет включён',
    lightOff: 'Свет выключен',
    lightOnA11y: 'Включить свет',
    lightOffA11y: 'Выключить свет',
  },
  presence: {
    sectionTitle: 'Кто дома',
    empty: 'Никого дома',
  },
  timeline: {
    sectionTitle: 'День дома',
    empty: 'Пока тихо — событий нет',
  },
  settings: {
    screenTitle: 'Настройки',
    syncTitle: 'Проверка данных',
    syncRefresh: 'Обновить данные',
    syncRefreshing: 'Загружаем…',
    haDevicesList: 'Список устройств',
    bedroomSensorsButton: 'Датчики спальни',
    reconnect: 'Изменить подключение к дому',
    bedroomSensors: {
      screenTitle: 'Датчики спальни',
      hint: 'Выбери устройства из Home Assistant. В приложении — только температура, влажность и CO₂.',
      notSelected: 'Не выбрано',
      notUsed: 'Не используется',
      change: 'Изменить',
      clear: 'Не использовать',
      unavailable: 'Сейчас недоступен',
    },
  },
  sensorPicker: {
    screenTitle: 'Выбор датчика',
    searchPlaceholder: 'Поиск по названию…',
    loading: 'Загрузка…',
    emptySearch: 'Ничего не найдено',
    emptyList: 'Нет датчиков',
    shownCount: 'Показано: {shown}',
    recommended: 'Подходят',
    other: 'Остальные',
    nonNumericHint: 'Похоже, это не датчик с цифрами',
  },
  onboarding: {
    title: 'Подключи дом',
    subtitle: 'Home Assistant остаётся за кадром — ты видишь только уют.',
    remoteOnlyHint:
      'Только удалённый URL? Оставь локальный пустым — подключимся сразу к Nabu Casa.',
    name: 'Название',
    localUrl: 'Локальный URL (LAN)',
    remoteUrl: 'Удалённый URL (опционально)',
    token: 'Токен доступа',
    localUrlPlaceholder: 'http://192.168.x.x:8123 (опционально)',
    remoteUrlPlaceholder: 'https://….ui.nabu.casa',
    save: 'Сохранить',
  },
  notFound: {
    screenTitle: 'Страница не найдена',
    title: 'Такой страницы нет',
    link: 'На главную',
  },
  haEntities: {
    screenTitle: 'Список устройств',
    hint: 'Скопируй идентификатор устройства в config — ищи свет, датчики, людей',
    searchPlaceholder: 'Поиск: свет, датчик, кухня…',
    loading: 'Загрузка…',
    shownCount: 'Показано: {shown} из {total}',
    emptySearch: 'Ничего не найдено',
    emptyList: 'Список пуст',
  },
} as const;
